apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argo-workflow-template
  namespace: default
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.project }}
  source:
    path: applications/spark-apps/hello-argo-workflow-template
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
