kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
data:
  dbt-profile: |
    kube_bq_jobs:
      outputs:
        dev:
          type: bigquery
          method: service-account
          project: kube-dbt
          dataset: dbt
          threads: 1
          keyfile: kube-dbt-86b509cb1b22.json
      target: dev
  