apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: dbt
    templates:
    - name: dbt
      serviceAccountName: dbt-user
      container:
        image: dbt-kube-demo:latest
        imagePullPolicy: Never
        command: [dbt, run]
        volumeMounts:
          - name: dbt-profile
            mountPath: /usr/app/profiles.yml
            subPath: profiles.yml
      volumes:
        - name: dbt-profile
          configMap:
            name: dbt-profile-cm
            items:
              - key: dbt-profile
                path: profiles.yml
