apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbt-user
  namespace: default
  labels:
    app: dbt
  annotations:
    annotations: {
      # Workload Identity binding between KSA and GSA
      # To be chnage with your project ID
      iam.gke.io/gcp-service-account: dbt-user@kube-dbt.iam.gserviceaccount.com,
    }