spark-operator:
  # Fix image tag due to using latest by default
  # https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1253
  # https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator
  image:
    tag: v1beta2-1.3.7-3.1.1
  webhook:
    enable: true
  podMonitor:
    enable: true
    labels:
      release: prometheus
