{{- if .Values.sparkHistoryServer.create -}}
{{- if .Values.sparkHistoryServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sparkHistoryServer.serviceAccountName" . }}
  labels:
    {{- include "sparkHistoryServer.labels" . | nindent 4 }}
  {{- with .Values.sparkHistoryServer.serviceAccount.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
