apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/jasonhue8183/k8s-spark-argocd.git'
    path: deployments/applications/spark-apps
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
