project: default
spec:
  source:
    repoURL: 'https://github.com/jasonhue8183/k8s-spark-argocd.git'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
