apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: default
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.project }}
  source:
    path: applications/platform/spark-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
