apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-prom
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "k8s-test/spark-prometheus:v1.2"
  imagePullPolicy: Never
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  securityContext: 
    runAsUser: 0
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    metricsPropertiesFile: /etc/metrics/conf/metrics.properties
    prometheus:
      configFile: /etc/metrics/conf/prometheus.yaml
      jmxExporterJar: /opt/spark/jars/jmx_prometheus_javaagent.jar
      port: 8090