apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/jasonhue8183/k8s-spark-argocd.git'
    path: applications/argocd
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
